#!/usr/bin/env python3
"""Generate src/context/genderspace_table.h from the calibration datasets.

Emits the acousticgender.space per-phoneme population stats (praat space) plus
robust-fitted linear maps from this tracker's formant units into praat units,
one map set per formant algorithm family (Filtered/Simple LPC vs DeepFormants).
Rerun after any tracker change, then rebuild.
"""
import json, os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "..", "genderspace")
STATS = json.load(open(f"{REPO}/stats.json"))

def load(path):
    rows = []
    with open(path) as f:
        hdr = next(f).rstrip("\n").split("\t")
        for line in f:
            c = dict(zip(hdr, line.rstrip("\n").split("\t")))
            rows.append({k: (c[k] if k in ("clip", "phoneme", "word") else
                             (float(c[k]) if c[k] else None)) for k in hdr})
    return rows

def fit_map(rows, i):
    ok = [r for r in rows if r[f"site_f{i}"]]
    x = np.array([r[f"trk_f{i}"] for r in ok])
    y = np.array([r[f"site_f{i}"] for r in ok])
    A = np.vstack([x, np.ones(len(x))]).T
    w = np.ones(len(y))
    beta = None
    for _ in range(6):
        Aw = A * w[:, None]
        beta = np.linalg.lstsq(Aw.T @ A, Aw.T @ y, rcond=None)[0]
        resid = np.abs(A @ beta - y)
        s = max(np.median(resid) * 1.4826, 1e-6)
        w = np.clip(1.5 * s / np.maximum(resid, 1e-9), None, 1.0)
    return beta

maps = {}
for tag, path in [("Lpc", f"{HERE}/dataset-dn.tsv"), ("Df", f"{HERE}/dataset-df.tsv")]:
    rows = load(path)
    maps[tag] = [fit_map(rows, 1), fit_map(rows, 2)]
    print(f"{tag}: F1 = {maps[tag][0][0]:.4f}*trk {maps[tag][0][1]:+.1f}, "
          f"F2 = {maps[tag][1][0]:.4f}*trk {maps[tag][1][1]:+.1f}  ({len(rows)} phones)")

phones = sorted(k for k in STATS if STATS[k] and len(STATS[k]) >= 3)

out = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "src", "context", "genderspace_table.h")
with open(out, "w") as f:
    f.write(
"""#ifndef MAIN_CONTEXT_GENDERSPACE_TABLE_H
#define MAIN_CONTEXT_GENDERSPACE_TABLE_H

// GENERATED by tools/genderspace-calib/gen_table.py -- do not edit by hand.
//
// Per-phoneme F1/F2 population statistics from acousticgender.space's
// stats.json (praat units), plus robust linear maps from this build's formant
// tracker units into praat units, fitted against the site's 21 reference
// clips (tools/genderspace-calib). Used to reproduce the site's resonance
// scale live; see GenderScore::siteResonance.

namespace Main::GenderSpaceTable {

    struct PhoneStat {
        double m1, s1, m2, s2;
    };

""")
    f.write(f"    inline constexpr int kNumPhones = {len(phones)};\n")
    f.write("    inline constexpr PhoneStat kPhoneStats[kNumPhones] = {\n")
    for ph in phones:
        st = STATS[ph]
        f.write(f"        {{ {st[1]['mean']:.4f}, {st[1]['stdev']:.4f}, "
                f"{st[2]['mean']:.4f}, {st[2]['stdev']:.4f} }}, // {ph}\n")
    f.write("    };\n\n")
    for tag in ("Lpc", "Df"):
        (a1, b1), (a2, b2) = maps[tag]
        f.write(f"    inline constexpr double kMap{tag}F1[2] = {{ {a1:.6f}, {b1:.4f} }};\n")
        f.write(f"    inline constexpr double kMap{tag}F2[2] = {{ {a2:.6f}, {b2:.4f} }};\n")
    f.write(
"""
    // Site resonance weights (their weights.json: F1 .732, F2 .268).
    inline constexpr double kW1 = 0.7321428571428571;
    inline constexpr double kW2 = 0.26785714285714285;

}

#endif // MAIN_CONTEXT_GENDERSPACE_TABLE_H
""")
print(f"wrote {out}")
