// GENERATED by tools/validate-dsp.mjs -- do not edit by hand.
//
// Derived for THIS tracker (browser implementation) rather than inherited from
// the desktop engine: calibration constants encode a tracker's measurement
// biases, so they do not transfer between implementations.
//
// Measured on acousticgender.space's 21 reference clips,
// 1987 paired phones. Leave-one-clip-out agreement with the official
// per-clip resonance medians: 0.0662 mean absolute error,
// worst clip 0.2175. Pitch vs praat: 6.5 Hz MAE.
// Weight anchors from the TransVoiceLessons light/heavy demonstrations.
export const WEB_CALIBRATION = {
    formantAnchors: [[420.0, 550.0], [1350.0, 1650.0], [2700.0, 3150.0]],
    praatMapF1: [0.876993, 60.9958],
    praatMapF2: [0.620765, 572.3370],
    weight: { light: -7.02, heavy: -3.23 },
    provisional: false,
};
