#!/usr/bin/env python3
"""Generate browser/src/dsp/phone-stats.js from acousticgender.space's stats.json.

Single source of truth: the same file that feeds the desktop engine's
genderspace_table.h. Run after changing the reference statistics.
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
stats = json.load(open(os.path.join(ROOT, "genderspace", "stats.json")))
weights = json.load(open(os.path.join(ROOT, "genderspace", "weights.json")))

phones = sorted(k for k in stats if stats[k] and len(stats[k]) >= 3)
rows = []
for ph in phones:
    st = stats[ph]
    rows.append("    [%.4f, %.4f, %.4f, %.4f], // %s" % (
        st[1]["mean"], st[1]["stdev"], st[2]["mean"], st[2]["stdev"], ph))

out = os.path.join(ROOT, "browser", "src", "dsp", "phone-stats.js")
with open(out, "w") as f:
    f.write("""// GENERATED by scripts/gen-web-tables.py -- do not edit by hand.
// Per-phoneme F1/F2 population statistics (praat units) from
// acousticgender.space's stats.json, used to place a voice on that project's
// resonance scale without knowing which phoneme is being spoken.
//
// Each row is [F1 mean, F1 stdev, F2 mean, F2 stdev].

export const PHONE_STATS = [
""")
    f.write("\n".join(rows))
    f.write("\n];\n\n")
    f.write("export const SITE_W1 = %.16f;\nexport const SITE_W2 = %.16f;\n"
            % (weights[0], weights[1]))
print(f"wrote {out}: {len(phones)} phonemes")
