#!/bin/bash
# Assemble a self-contained static site from browser/, ready to hand to any
# static host. Nothing here is host-specific: the output is a directory of files
# that works at a domain root or under a subpath, because every asset the page
# fetches is addressed relative to the file that asks for it.
#
# It gathers three things the working tree keeps out of git, plus one the AGPL
# requires of a network deployment:
#
#   vendor/      onnxruntime-web, from browser/node_modules (npm ci) or browser/vendor
#   models/      the optional gender-probe ONNX, if a copy is around
#   LICENSE.txt  AGPL-3.0, the terms browser/ is under
#   source/      the corresponding source, offered from the page footer
#
# The model is genuinely optional; the app hides the listener reading when it is
# absent and the DSP path does not touch it.
#
#   browser/tools/build-static.sh [outdir]        # default browser/dist
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${1:-$ROOT/browser/dist}"
SRCNAME=voice-lab-browser-src

say() { printf '  %s\n' "$1"; }

rm -rf "$OUT"
mkdir -p "$OUT"

printf '\n=== app\n'
cp "$ROOT/browser/index.html" "$OUT/"
cp -r "$ROOT/browser/src" "$OUT/"

# The shared analysis core, compiled from the desktop engine's own sources.
# Without this the analysis worker has nothing to import and the page loads but
# never measures anything.
# Reference-speaker medians for the genderspace view.
if [ -d "$ROOT/browser/data" ]; then
    cp -r "$ROOT/browser/data" "$OUT/"
fi

if [ -f "$ROOT/browser/wasm/voicelab.wasm" ]; then
    cp -r "$ROOT/browser/wasm" "$OUT/"
else
    echo "ERROR: browser/wasm/voicelab.wasm missing; run scripts/build-wasm.sh" >&2
    exit 1
fi
say "index.html, src/"

printf '\n=== onnxruntime-web (vendor/)\n'
ORT_DIST="$ROOT/browser/node_modules/onnxruntime-web/dist"
if [ -d "$ORT_DIST" ]; then
    mkdir -p "$OUT/vendor"
    # The wasm-only bundle, which is what gender-probe.js imports. The .jsep
    # variants are the WebGPU provider, deliberately unused (it builds a session
    # on this quantised graph and then fails at run time), so they are ~13 MB of
    # payload nobody would fetch.
    cp "$ORT_DIST/ort.wasm.min.mjs" "$OUT/vendor/"
    cp "$ORT_DIST"/ort-wasm-simd-threaded.mjs "$OUT/vendor/"
    cp "$ORT_DIST"/ort-wasm-simd-threaded.wasm "$OUT/vendor/"
    say "from node_modules ($(du -sh "$OUT/vendor" | cut -f1))"
elif [ -d "$ROOT/browser/vendor" ]; then
    cp -r "$ROOT/browser/vendor" "$OUT/"
    say "from browser/vendor ($(du -sh "$OUT/vendor" | cut -f1))"
else
    say "absent: run 'npm ci' in browser/ first. Building without the neural probe."
fi

printf '\n=== gender-probe model (models/)\n'
MODEL=
for cand in "$ROOT/browser/models/ecapa_gender_int8.onnx" "$ROOT/ml/models/ecapa_gender_int8.onnx"; do
    [ -f "$cand" ] && MODEL="$cand" && break
done
if [ -n "$MODEL" ]; then
    mkdir -p "$OUT/models"
    cp "$MODEL" "$OUT/models/"
    say "$(basename "$MODEL") ($(du -h "$MODEL" | cut -f1)), from ${MODEL#$ROOT/}"
else
    say "absent. The app will hide the listener-model reading; everything else works."
    say "build it with: ml/.venv/bin/python -m gender_probe.fetch_model"
fi

printf '\n=== licence and source offer\n'
# .txt, so a static host serves it as text/plain and the footer link shows the
# licence in the browser instead of downloading an extensionless file.
cp "$ROOT/genderspace/LICENSE" "$OUT/LICENSE.txt"

# The corresponding source for what is being served: the app (already shipped
# unminified), the calibration harness that derives its constants, the generator
# for the derived tables and the upstream statistics it reads, and the notes.
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$STAGE/$SRCNAME"
tar -c -C "$ROOT" \
    browser/index.html browser/src browser/tools \
    browser/package.json browser/package-lock.json \
    scripts/gen-web-tables.py \
    genderspace/stats.json genderspace/weights.json \
    docs/browser.md docs/LICENSING.md docs/deploy.md \
    | tar -x -C "$STAGE/$SRCNAME"
cp "$ROOT/genderspace/LICENSE" "$STAGE/$SRCNAME/LICENSE"

REV="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
cat > "$STAGE/$SRCNAME/README.md" <<EOF
# voice-lab, browser build: corresponding source

The complete source for the page you were served, at revision \`$REV\`.

It is under the GNU AGPL-3.0 (see LICENSE), because it carries
acousticgender.space's resonance scale and per-phoneme population statistics and
reproduces its genderspace visualisation. \`docs/LICENSING.md\` explains which
part of the wider project is under which terms.

To run it:

    cd browser && npm ci && tools/build-static.sh
    python3 -m http.server 8181 --directory dist --bind 127.0.0.1

\`browser/src/dsp/phone-stats.js\` is generated by \`scripts/gen-web-tables.py\`
from the two upstream statistics files included here.
\`browser/tools/validate-dsp.mjs\` re-derives \`src/dsp/calibration.js\` from
reference recordings; \`docs/browser.md\` describes both.

The optional perceived-gender model is not included: it is a third-party
download under its own licence, built by \`ml/gender_probe/fetch_model.py\` from
\`JaesungHuh/voice-gender-classifier\`.
EOF

mkdir -p "$OUT/source"
tar -czf "$OUT/source/$SRCNAME.tar.gz" -C "$STAGE" "$SRCNAME"
say "LICENSE.txt, source/$SRCNAME.tar.gz ($(du -h "$OUT/source/$SRCNAME.tar.gz" | cut -f1))"

# The footer carries the offer only in a built site; served straight out of
# browser/ for local use there is nothing to offer and no one to offer it to.
OFFER='<a href="./source/'"$SRCNAME"'.tar.gz">Source</a> (<a href="./LICENSE.txt">AGPL&#8209;3.0</a>).'
MODEL_STATE=absent
[ -n "$MODEL" ] && MODEL_STATE=present
python3 - "$OUT/index.html" "$OFFER" "$MODEL_STATE" <<'PY'
import sys
path, offer, model_state = sys.argv[1], sys.argv[2], sys.argv[3]
html = open(path).read()

marker = '<!--SOURCE-OFFER-->'
if marker not in html:
    sys.exit(f'{path}: {marker} marker missing; footer would ship without the source offer')
html = html.replace(marker, offer)

# Tell the page whether the optional model is deployed, so it never has to find
# out by asking for a file that is not there.
head = '<head>'
if head not in html:
    sys.exit(f'{path}: no <head> to declare the model state in')
html = html.replace(head, f'{head}\n<meta name="voicelab-model" content="{model_state}">', 1)

open(path, 'w').write(html)
PY
say "footer source offer injected, model declared $MODEL_STATE"

printf '\n%s, %s total\n' "$OUT" "$(du -sh "$OUT" | cut -f1)"
